+ fhir examples
solid/data-interoperability-panel pull request #135
Opened 2021-07-01 13:50 UTC by ericprud

In progress

2021-07-01 22:02 UTC, TallTed requested changes
A few random nits

2021-07-01 22:02 UTC, TallTed commented on proposals/primer/index.bs
> +The referenced ../Location/HomeAddress contains contact information and addresses:
```suggestion
The referenced <code>../Location/HomeAddress</code> contains contact information and addresses:
```

2021-07-02 14:35 UTC, ericprud commented on proposals/primer/snippets/bob.example/fhir-CarePlan-DataRegistration.ttl
> +  interop:registeredShapeTree fhirshapes:CarePlanContainer ;
i pointed to the data reg at CarePlanContainer. Is that correct?

2021-07-02 17:13 UTC, TallTed commented on proposals/primer/index.bs
> +1. A HEAD on <code>A-CarePlan-F/A-HypoglycemiaManagement-F</code> includes a Link: header rel=<code>http://shapetrees.org/#ShapeTreeLocator</code> pointing to <code>A-HypoglycemiaManagement-F?stloc#l
```suggestion
1. A <code>HEAD</code> on <code>A-CarePlan-F/A-HypoglycemiaManagement-F</code> includes a <code>Link:</code> header <code>rel</code>=<code>http://shapetrees.org/#ShapeTreeLocator</code> pointing to <code>A-HypoglycemiaManagement-F?stloc#locator</code>.
```

2021-07-02 17:56 UTC, TallTed commented on proposals/primer/index.bs
> +we would need to start a path from a defined shape, e.g.
```suggestion
we would need to start a path from a defined shape, e.g.,
```

2021-07-02 18:37 UTC, elf-pavlik commented on proposals/primer/index.bs
> +The CarePlan data registration would reference the <code>/data/A-CarePlan-F/<code> container which includes <code>A-HypoglycemiaManagement-F</code> and <code>A-Wellness-F</code> mentioned above:
```suggestion
The CarePlan data registration would reference the <code>/data/A-CarePlan-F/</code> container which includes <code>A-HypoglycemiaManagement-F</code> and <code>A-Wellness-F</code> mentioned above:
```

2021-07-02 18:46 UTC, elf-pavlik commented on proposals/primer/snippets/bob.example/fhir-CarePlan-DataRegistration.ttl
> +  interop:registeredShapeTree fhirshapes:CarePlan ;
```suggestion
  interop:registeredShapeTree fhirshapeTree:CarePlan ;
```

2021-07-02 18:47 UTC, elf-pavlik commented
Looks good @ericprud, thank you! Could you please also add Data Registration for `fhirshapeTree:Location`

2021-07-02 21:16 UTC, ericprud commented
> Looks good @ericprud, thank you! Could you please also add Data Registration for `fhirshapeTree:Location`?

I think that would imply that we need a Shape Tree Locator, a Shape Tree, and finally a schema for it. I wonder where to draw the line.

> I also don't understand why do you need `fhirshapeTree:CarePlanContainer` if it doesn't have any Data Registration and Data Instance?

It provides the ShapeTree for <http://bob.example/data/A-CarePlan-F/> and is referenced as the root of the locator.

2021-07-02 21:21 UTC, ericprud commented on proposals/primer/index.bs
> +1. A HEAD on <code>A-CarePlan-F/A-HypoglycemiaManagement-F</code> includes a Link: header rel=<code>http://shapetrees.org/#ShapeTreeLocator</code> pointing to <code>A-HypoglycemiaManagement-F?stloc#l
this is now in a <pre/>

2021-07-06 14:24 UTC, elf-pavlik commented on proposals/primer/snippets/bob.example/fhir-CarePlan-DataRegistration.ttl
> +  interop:hasRegisteredDataInstance
We should clarify if we use this on `ldp:contains`, discussing it now during the call with @justinwb

2021-07-07 13:13 UTC, elf-pavlik commented on proposals/primer/snippets/bob.example/fhir-CarePlan-DataRegistration.ttl
> +  interop:hasRegisteredDataInstance
```suggestion
  ldp:contains
```

I think we should use this one at least for now, I may create separate issue to discuss it futher

2021-07-07 13:16 UTC, elf-pavlik commented
@ericprud @justinwb I think we should merge this one later today. We can always create issue to add missing data registration. BTW we could at least add snippet for data registration without including it in primer document.

2021-07-07 18:43 UTC, ericprud commented
I added the Location ShapeTreeLocator and DataRegistration. Should be good to go, though the preview isn't showing up ('cause I'm so impatient)

2021-07-08 15:04 UTC, merged