Resource indication
solid/data-interoperability-panel pull request #320
Opened 2023-11-06 14:51 UTC by elf-pavlik

This PR mostly closes #138 

It also moves the detailed app authorization sequence diagram to the primers since it is a non-normative explainer.

HTML previews and diffs (snippets seem to get messed up in diffs):
* specification [preview](https://deploy-preview-320--data-interoperability-panel.netlify.app/specification/) | [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fsolid.github.io%2Fdata-interoperability-panel%2Fspecification%2F&doc2=https%3A%2F%2Fdeploy-preview-320--data-interoperability-panel.netlify.app%2Fspecification%2F)
* application primer [preview](https://deploy-preview-320--data-interoperability-panel.netlify.app/primer/application) | [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fsolid.github.io%2Fdata-interoperability-panel%2Fprimer%2Fapplication.html&doc2=https%3A%2F%2Fdeploy-preview-320--data-interoperability-panel.netlify.app%2Fprimer%2Fapplication)
* authorization agent primer [preview](https://deploy-preview-320--data-interoperability-panel.netlify.app/primer/authorization-agent) | [diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fsolid.github.io%2Fdata-interoperability-panel%2Fprimer%2Fauthorization-agent.html&doc2=https%3A%2F%2Fdeploy-preview-320--data-interoperability-panel.netlify.app%2Fprimer%2Fauthorization-agent)

2023-11-06 19:30 UTC, TallTed requested changes
Various punctuation, spelling, grammar, etc., editorial fixes

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Alice's Authorization Agent dereferences the supplied Projectron identity, retrieving Projection's
```suggestion
          <td>Alice's Authorization Agent dereferences the supplied Projectron identifier, retrieving Projectron's
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Projectron redirects Alice to her Authorization Agent, supplying its identity for context</td>
```suggestion
          <td>Projectron redirects Alice to her Authorization Agent, supplying its identifier for context.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Projectron asks Alice's Authorization Agent again for a Projectron Application Registration</td>
```suggestion
          <td>Projectron again asks Alice's Authorization Agent for a Projectron Application Registration.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Alice's Authorization Agent finds the newly created Projectron Application Registration in the Agent Registry in Alice's Pod</td>
```suggestion
          <td>Alice's Authorization Agent finds the newly created Projectron Application Registration in the Agent Registry in Alice's Pod.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Alice's Authorization Agent provides the URI of the Application Registration to Projectron</td>
```suggestion
          <td>Alice's Authorization Agent provides the URI of the Application Registration to Projectron.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/app-authorization-flow.bs
> +          <td>Projectron learns what access it received through the Access Grant in Alice's Projectron Application Registration</td>
```suggestion
          <td>Projectron learns what access it received through the Access Grant in Alice's Projectron Application Registration.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/application.bs
> +In case where application hasn't been registered yet it needs to initiate flow with Authorization Agent.
```suggestion
In cases where an application hasn't been registered yet, it needs to initiate the flow with the Authorization Agent.
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/application.bs
> +After successful flow application will be able to discover its registration.
```suggestion
After successful flow, the application will be able to discover its registration.
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/application.bs
> +indication is available.
```suggestion
When the application has already been registered, and the user wants to
initiate a sharing-specific [[#data-instance]], an authorization flow with resource
indication is available.
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/authorization-agent.bs
>  An Access Grant is immutable, it never gets updated, instead it can be only replaced with a newer Access Grant.
```suggestion
An Access Grant is immutable — it never gets updated; it can only be replaced, by a newer Access Grant.
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/authorization-agent.bs
> +initiate sharing specific [[#data-instance]], an authorization flow with resource
```suggestion
When the application has already been registered, and the user wants to
initiate a sharing-specific [[#data-instance]], an authorization flow with resource
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/diagrams/application-requests-access-flow.seq.mmd
> +    Note over Alice's Identity Document,Projectron: 3. Projectron discovers Alice's Authorization Agent in her WebID Document
```suggestion
    participant Alice's WebID Document
    Note over Projectron: 1. 👩 Alice decides to use Projectron
    Note over Projectron: 2. 👩 Alice authenticates with her WebID
    Note over Alice's WebID Document,Projectron: 3. Projectron discovers Alice's Authorization Agent in her WebID Document
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/resource-indication-flow.bs
> +          also select modes of access for each inherited shape tree.</td>
```suggestion
          <td>Alice chooses all the social agents with which she wants to share the selected project,
          as well as modes of access for all selected agents. If the shape tree has references (e.g., tasks) she can
          also select modes of access for each inherited shape tree.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/resource-indication-flow.bs
> +          Application profile graph from the Identity Profile Document,
```suggestion
          <td>Alice's Authorization Agent dereferences the supplied Projectron WebID, retrieving Projection's
          Application profile graph from the WebID Profile Document,
```

2023-11-06 19:30 UTC, TallTed commented on proposals/primer/resource-indication-flow.bs
> +          <td>Alice's Authorization Agent redirects her back to Projectron now that the project has been shared.</td>
```suggestion
          <td>Alice's Authorization Agent redirects her back to Projectron, now that the project has been shared.</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/specification/application.bs
> +      to the application after completing authorization</td>
```suggestion
      to the application, after completing authorization</td>
```

2023-11-06 19:30 UTC, TallTed commented on proposals/specification/data-authorization.bs
> +An [=Application=] capable of redirecting, should redirect the user to
```suggestion
An [=Application=] capable of redirecting, should redirect the user to the
```

2023-11-07 14:34 UTC, justinwb approved these changes
✅ all looks good to me!

2023-11-07 20:59 UTC, merged